name: cd-azure

on:
  push:
    paths:
      - ".github/workflows/cd-azure.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: ./build-push.sh
        working-directory: ./api

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: build
    steps:
      - run: echo "Deploying to Azure...!!"
